# -*- coding: utf-8 -*-
"""Py_OS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vq4NVS4_YqtweVbycIZO2VdEY0YvvvuO

# ReadMe
OS모듈의 이용법

참고 : https://jakely.tistory.com/56
"""

import os
import re

## 현재 폴더 위치를 보여준다 (get current working directory의 약자)
os.getcwd()

## 파일 위치를 변경한다 (change directory)
os.chdir('C:\\Users\\user\\Desktop\\test')

## 현재 폴더 위치에 있는 모든 폴더/파일 나열
os.listdir()

## 현재 폴더 위치에 있는 모든 폴더/파일 중 폴더만 나열
for f in os.listdir():
    if os.path.isdir(f):
        print(f)

## 현재 폴더 위치에 있는 모든 폴더/파일 중 특정 확장자로 끝나는 파일만 나열
## 아래 코드의 경우 .png .jpg .jpeg  파일만 가져온다
for f in os.listdir():
    if f.endswith(('.png' , '.jpg', '.jpeg')):
        print(f)

## 파일 삭제
os.remove('캡처.PNG')

## 폴더 삭제
os.rmdir('C:/Users/jake1/Desktop/새 폴더')

## 파일 이름 변경
os.rename('변경전.txt' , '변경후.txt')

## 특정 파일 삭제
## 아래 코드의 경우 2019가 파일명에 있는 모든 파일 제거
### ex) '기말족보_2019_01_01.txt', '사진_2019_04_30.jpg'
for f in os.listdir():
    if f.contains('2019'):
        os.remove(f)